language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install --upgrade pip setuptools wheel
  - pip install codecov
  - pip install -e .[test]
script:
  - coverage run --source=sat_api_client -m pytest -v
after_success:
  - codecov
